### ISSUE TITLE
add findLongestPrefix

### ISSUE THREAD

**Issue by aavogt** [meooow25/parser-regex#19]
I like `Data.List.stripPrefix`. regex-applicative calls their generalization of it [findLongestPrefix](https://hackage.haskell.org/package/regex-applicative-0.3.4/docs/Text-Regex-Applicative.html#v:findLongestPrefix).

**Comment by meooow25** [comment]
Might I ask what is your use case for this?
It's not clear to me whether you're looking for a `stripPrefix` or `stripLongestPrefix`.

**Comment by aavogt** [comment]
I use findLongestPrefix in this [haskell source preprocessor](https://github.com/aavogt/HListPP/blob/master/HListPP.hs#L33). Elsewhere in that file I use Data.List.stripPrefix. That HListPP is probably obsoleted by extensions like OverloadedRecordDot, but I'm working on a similar [preprocessor adding c syntax](https://gist.github.com/aavogt/a080ea1a9cf855a879462c902ee6f585). Because `Regex.List.find` already conflicts with `Data.List.find`, I think you could add

```haskell
stripPrefix :: RE c a -> [c] -> Maybe [c]
findPrefix :: RE c a -> [c] -> Maybe (a, [c])
```
In my case, I would use `Regex.List.findPrefx` because I have to keep track of the input that was consumed.

**Comment by meooow25** [comment]
Thanks for the link to your code. I've also thought about this function for a bit.

To give a simple answer, one possible definition of `findPrefix` is

```hs
findPrefix :: RE c a -> [c] -> Maybe (a, [c])
findPrefix re = reParse (liftA2 (,) re manyList)
```

It is easy to define by a user who needs it.  
But I am reluctant to add it to the library, because doing this operation repeatedly would be inefficient. And it does seem to encourage that pattern. It is inefficient because it reconstructs the tail of the list after the match. Doing this repeatedly is quadratic in the length of the list.

So why not add a separate runner that tries to preserve the tail, like `regex-applicative`'s `findLongestPrefix`?  
Because

1. There is currently only one way to run a regex on a list, which is `parse`, and that runs on the whole list. Any other function present for convenience (`reParse`, `find`, `replace`, etc.) uses it under the hood. This simple model is easy to understand and I like it.
2. Even a separate runner like `regex-applicative`'s `findLongestPrefix` can take linear time in the worst case, depending on the regex and the list. Neither of these libraries lend themselves well to the style of "parse a prefix of a list, then continue to parse the rest". (Side note: `Data.List.stripPrefix` does fit well in this pattern, it is only linear in the prefix, and does not touch the rest of the list)

---

Now, if I had to implement your preprocessor's `takeQual` with `parser-regex`, I would not use the above definition of `findPrefix` because of the described inefficiency.

Instead, I would try one of two things:

1. Extract the token separately from parsing it.

```hs
takeQual x = case span isValidIdentChar x of
  (y, rest) -> case reParse qualIdent y of
    Nothing -> (y, rest)
    Just a -> (addLabel a, rest)

isValidIdentChar = ...
```

2. Or, do away with the manual parsing bits and put everything in a regex

```hs
re = fmap concat $ many $ asum
  [ string
  , char
  , comment
  , addLabel <$> qualIdent
  , anySingle
  ]

comment = toMatch $ list "{-" *> manyListMin *> list "-}"
string = ...
char = ...
```

**Comment by meooow25** [comment]
I've looked around a bit more on this issue, and I learnt that this is a common technique for tokenization/lexing of languages. It seems that the quadratic complexity does not usually pose a problem, perhaps because 1. the language is static and if lexing takes forever you would notice, and 2. you would need a large enough source file to see the difference.

While I can now see better why someone would want `findLongestPrefix`, I still don't like the idea of putting a potential footgun in the library.

For lexing in particular, parsing using `many tokenRe` might be an alternative. The only thing you lose this way is streaming, i.e. generating tokens one at a time.

Should someone really need it, it is possible to define `findLongestPrefix` for lists using the primitives in `Regex.Base`. It is not possible for `Text` currently, but I will expose the internals in the next release to make this possible.

---

I'll leave a concrete example of how it's quite easy to shoot yourself with `findLongestPrefix`.

```hs
import Data.List
import Text.Regex.Applicative

re = sym 'a' <|> (many (sym 'a') *> sym 'b')

-- O(n^2)
parse :: String -> String
parse = unfoldr (findLongestPrefix re)

n = 100000

main = print $ parse (replicate n 'a')
```

The same is true for various lexing libraries. Here is an [alex](https://hackage.haskell.org/package/alex) program with the same behavior.

```hs
{
}

%wrapper "basic"

tokens :-
  a   { \_ -> 'a' }
  a*b { \_ -> 'b' }

{
-- O(n^2)
parse :: String -> String
parse = alexScanTokens

n = 100000

main = print $ parse (replicate n 'a')
}
```

**Comment by aavogt** [comment]
The readme has:
> parser-regex attempts to be a more fully-featured library built on the ideas of regex-applicative.

Maybe it should be something like:
> parser-regex attempts to be a more principled but less fully-featured library built on the ideas of regex-applicative.
